-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 17:16:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `dfmsDB` ;
CREATE DATABASE IF NOT EXISTS `dfmsDB` ;
USE `dfmsDB` ;
-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

CREATE TABLE IF NOT EXISTS `accounts` (
  `account_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base` ;

CREATE TABLE IF NOT EXISTS `base` (
  `base_id` INT(3) ZEROFILL NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `rpa_count` INT NULL,
  `maintainer_count` INT NULL,
  PRIMARY KEY (`base_id`),
  UNIQUE INDEX `base_id_UNIQUE` (`base_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organization` ;

CREATE TABLE IF NOT EXISTS `organization` (
  `organization_id` INT(3) ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `base` INT(3) ZEROFILL NULL,
  PRIMARY KEY (`organization_id`),
  INDEX `FK_ORGANIZATION_BASE_idx` (`base` ASC) VISIBLE,
  UNIQUE INDEX `organization_id_UNIQUE` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `FK_ORGANIZATION_BASE`
    FOREIGN KEY (`base`)
    REFERENCES `base` (`base_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pilot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pilot` ;

CREATE TABLE IF NOT EXISTS `pilot` (
  `pilot_id` INT(6) ZEROFILL NOT NULL,
  `organization` INT(3) ZEROFILL NULL,
  `last_training` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pilot_id`),
  INDEX `FK_PILOT_ORGANIZATION_idx` (`organization` ASC) VISIBLE,
  UNIQUE INDEX `pilot_id_UNIQUE` (`pilot_id` ASC) VISIBLE,
  CONSTRAINT `PKFK_PILOT_ACCOUNT`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PILOT_ORGANIZATION`
    FOREIGN KEY (`organization`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensor_operator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sensor_operator` ;

CREATE TABLE IF NOT EXISTS `sensor_operator` (
  `sensor_id` INT(6) ZEROFILL NOT NULL,
  `organization` INT(3) ZEROFILL NULL,
  `last_training` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`sensor_id`),
  INDEX `FK_SENSOR_ORGANIZATION_idx` (`organization` ASC) VISIBLE,
  UNIQUE INDEX `sensor_id_UNIQUE` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `PKFK_SENSOR_ACCOUNT`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SENSOR_ORGANIZATION`
    FOREIGN KEY (`organization`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maintainer` ;

CREATE TABLE IF NOT EXISTS `maintainer` (
  `maintainer_id` INT(6) ZEROFILL NOT NULL,
  `organization` INT(3) ZEROFILL NULL,
  `last_training` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `base` INT(3) ZEROFILL NULL,
  PRIMARY KEY (`maintainer_id`),
  INDEX `FK_MAINTAINER_ORGANIZATION_idx` (`organization` ASC) VISIBLE,
  INDEX `FK_MAINTAINER_BASE_idx` (`base` ASC) VISIBLE,
  UNIQUE INDEX `maintainer_id_UNIQUE` (`maintainer_id` ASC) VISIBLE,
  CONSTRAINT `PKFK_MAINTAINER_ACCOUNT`
    FOREIGN KEY (`maintainer_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MAINTAINER_ORGANIZATION`
    FOREIGN KEY (`organization`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MAINTAINER_BASE`
    FOREIGN KEY (`base`)
    REFERENCES `base` (`base_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `remotely_piloted_aircraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `remotely_piloted_aircraft` ;

CREATE TABLE IF NOT EXISTS `remotely_piloted_aircraft` (
  `rpa_id` INT(3) ZEROFILL NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `pilot` INT(6) ZEROFILL NULL,
  `sensor_operator` INT(6) ZEROFILL NULL,
  `maintainer` INT(6) ZEROFILL NULL,
  `status` VARCHAR(45) NULL,
  `base` INT(3) ZEROFILL NULL,
  PRIMARY KEY (`rpa_id`),
  INDEX `FK_RPA_PILOT_idx` (`pilot` ASC) VISIBLE,
  INDEX `FK_RPA_SENSOR_idx` (`sensor_operator` ASC) VISIBLE,
  INDEX `FK_RPA_MAINTAINER_idx` (`maintainer` ASC) VISIBLE,
  INDEX `FK_RPA_BASE_idx` (`base` ASC) VISIBLE,
  UNIQUE INDEX `rpa_id_UNIQUE` (`rpa_id` ASC) VISIBLE,
  CONSTRAINT `FK_RPA_PILOT`
    FOREIGN KEY (`pilot`)
    REFERENCES `pilot` (`pilot_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RPA_SENSOR`
    FOREIGN KEY (`sensor_operator`)
    REFERENCES `sensor_operator` (`sensor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RPA_MAINTAINER`
    FOREIGN KEY (`maintainer`)
    REFERENCES `maintainer` (`maintainer_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RPA_BASE`
    FOREIGN KEY (`base`)
    REFERENCES `base` (`base_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planner` ;

CREATE TABLE IF NOT EXISTS `planner` (
  `planner_id` INT(6) ZEROFILL NOT NULL,
  `organization` INT(3) ZEROFILL NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`planner_id`),
  INDEX `FK_PLANNER_ORGANIZATION_idx` (`organization` ASC) VISIBLE,
  UNIQUE INDEX `planner_id_UNIQUE` (`planner_id` ASC) VISIBLE,
  CONSTRAINT `PKFK_PLANNER_ACCOUNT`
    FOREIGN KEY (`planner_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PLANNER_ORGANIZATION`
    FOREIGN KEY (`organization`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payload` ;

CREATE TABLE IF NOT EXISTS `payload` (
  `payload_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `weightlbs` INT(8) NULL,
  `pylon_count` TINYINT(2) NULL,
  PRIMARY KEY (`payload_id`),
  UNIQUE INDEX `payload_id_UNIQUE` (`payload_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight_plan` ;

CREATE TABLE IF NOT EXISTS `flight_plan` (
  `plan_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `planner` INT(6) ZEROFILL NULL,
  `waypoints` VARCHAR(45) NULL,
  `launch_base` INT(3) ZEROFILL NULL,
  `recovery_base` INT(3) ZEROFILL NULL,
  `payload` INT(6) ZEROFILL NULL,
  PRIMARY KEY (`plan_id`),
  INDEX `FK_PLAN_PLANNER_idx` (`planner` ASC) VISIBLE,
  INDEX `FK_LAUNCH_BASE_idx` (`launch_base` ASC) VISIBLE,
  INDEX `FK_RECOVERY_BASE_idx` (`recovery_base` ASC) VISIBLE,
  INDEX `FK_PLAN_PAYLOAD_idx` (`payload` ASC) VISIBLE,
  UNIQUE INDEX `plan_id_UNIQUE` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `FK_PLAN_PLANNER`
    FOREIGN KEY (`planner`)
    REFERENCES `planner` (`planner_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LAUNCH_BASE`
    FOREIGN KEY (`launch_base`)
    REFERENCES `base` (`base_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RECOVERY_BASE`
    FOREIGN KEY (`recovery_base`)
    REFERENCES `base` (`base_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PLAN_PAYLOAD`
    FOREIGN KEY (`payload`)
    REFERENCES `payload` (`payload_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mission` ;

CREATE TABLE IF NOT EXISTS `mission` (
  `mission_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `flight_plan` INT(6) ZEROFILL NULL,
  `rpa` INT(3) ZEROFILL NULL,
  `task` VARCHAR(45) NULL,
  PRIMARY KEY (`mission_id`),
  INDEX `FK_MISSION_PLAN_idx` (`flight_plan` ASC) VISIBLE,
  INDEX `FK_MISSION_RPA_idx` (`rpa` ASC) VISIBLE,
  UNIQUE INDEX `mission_id_UNIQUE` (`mission_id` ASC) VISIBLE,
  CONSTRAINT `FK_MISSION_PLAN`
    FOREIGN KEY (`flight_plan`)
    REFERENCES `flight_plan` (`plan_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MISSION_RPA`
    FOREIGN KEY (`rpa`)
    REFERENCES `remotely_piloted_aircraft` (`rpa_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sortie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sortie` ;

CREATE TABLE IF NOT EXISTS `sortie` (
  `sortie_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `mission` INT(6) ZEROFILL NOT NULL,
  `rpa` INT(3) ZEROFILL NOT NULL,
  `launch_time` DATETIME NULL,
  `recovery_time` DATETIME NULL,
  PRIMARY KEY (`sortie_id`),
  INDEX `FK_SORTIE_RPA_idx` (`rpa` ASC) VISIBLE,
  INDEX `FK_SORTIE_MISSION_idx` (`mission` ASC) VISIBLE,
  UNIQUE INDEX `sortie_id_UNIQUE` (`sortie_id` ASC) VISIBLE,
  CONSTRAINT `FK_SORTIE_RPA`
    FOREIGN KEY (`rpa`)
    REFERENCES `remotely_piloted_aircraft` (`rpa_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SORTIE_MISSION`
    FOREIGN KEY (`mission`)
    REFERENCES `mission` (`mission_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maintenance_appointment` ;

CREATE TABLE IF NOT EXISTS `maintenance_appointment` (
  `appointment_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `rpa` INT(3) ZEROFILL NULL,
  `maintainer` INT(6) ZEROFILL NULL,
  `scheduled_time` DATETIME NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `FK_APPOINTMENT_RPA_idx` (`rpa` ASC) VISIBLE,
  INDEX `FK_APPOINTMENT_MAINTAINER_idx` (`maintainer` ASC) VISIBLE,
  UNIQUE INDEX `appointment_id_UNIQUE` (`appointment_id` ASC) VISIBLE,
  CONSTRAINT `FK_APPOINTMENT_RPA`
    FOREIGN KEY (`rpa`)
    REFERENCES `remotely_piloted_aircraft` (`rpa_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_APPOINTMENT_MAINTAINER`
    FOREIGN KEY (`maintainer`)
    REFERENCES `maintainer` (`maintainer_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maintenance_log` ;

CREATE TABLE IF NOT EXISTS `maintenance_log` (
  `rpa` INT(3) ZEROFILL NOT NULL,
  `appointment` INT(6) ZEROFILL NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  INDEX `FK_LOG_APPOINTMENT_idx` (`appointment` ASC) VISIBLE,
  PRIMARY KEY (`rpa`),
  UNIQUE INDEX `rpa_UNIQUE` (`rpa` ASC) VISIBLE,
  CONSTRAINT `PKFK_MAINTLOG_RPA`
    FOREIGN KEY (`rpa`)
    REFERENCES `remotely_piloted_aircraft` (`rpa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LOG_APPOINTMENT`
    FOREIGN KEY (`appointment`)
    REFERENCES `maintenance_appointment` (`appointment_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devices` ;

CREATE TABLE IF NOT EXISTS `devices` (
  `device_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `account` INT(6) ZEROFILL NULL,
  `last_login` DATETIME NULL,
  `still_authorized` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`device_id`),
  INDEX `FK_DEVICE_ACCOUNT_idx` (`account` ASC) VISIBLE,
  UNIQUE INDEX `device_id_UNIQUE` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_DEVICE_ACCOUNT`
    FOREIGN KEY (`account`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight_log` ;

CREATE TABLE IF NOT EXISTS `flight_log` (
  `rpa` INT(3) ZEROFILL NOT NULL AUTO_INCREMENT,
  `sortie` INT(6) ZEROFILL NULL,
  `flight_time` TIME NOT NULL,
  PRIMARY KEY (`rpa`),
  INDEX `FK_LOG_SORTIE_idx` (`sortie` ASC) VISIBLE,
  UNIQUE INDEX `rpa_UNIQUE` (`rpa` ASC) VISIBLE,
  CONSTRAINT `PKFK_FLIGHTLOG_RPA`
    FOREIGN KEY (`rpa`)
    REFERENCES `remotely_piloted_aircraft` (`rpa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LOG_SORTIE`
    FOREIGN KEY (`sortie`)
    REFERENCES `sortie` (`sortie_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
